# Generated by Django 4.2.3 on 2023-10-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piloot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_E', models.AutoField(primary_key=True, serialize=False)),
                ('nome_empresa', models.TextField(max_length=255)),
            ],
        ),
    ]
