# Generated by Django 4.2.3 on 2023-10-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piloot_app', '0002_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresadfv',
            name='tipo',
            field=models.IntegerField(),
        ),
    ]
