# Generated by Django 4.2.3 on 2023-10-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piloot_app', '0006_alter_empresadfv_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_op', models.TextField(max_length=255)),
            ],
        ),
    ]
