# Generated by Django 4.2.3 on 2023-10-23 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('piloot_app', '0009_alter_empresadfv_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresadfv',
            name='empresa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='piloot_app.empresa'),
        ),
        migrations.CreateModel(
            name='tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_escolhido', models.TextField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
